In [1]:
import numpy as np

In [2]:
#%%timeit
quadrati = []
quadrati = np.arange(0,1000000)**2

### Crare gli array unidimensionali

In [3]:
array_di_zeri = np.zeros(10)
array_di_zeri

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
array_di_zeri.dtype

dtype('float64')

In [5]:
array_di_zeri_int = np.zeros(10,dtype=np.int8)
array_di_zeri_int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [6]:
array_di_uni = np.ones(10)
array_di_uni

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
array_di_cinque = np.ones(10)*5 # BROADCAST
array_di_cinque

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
lista = [1,2,3,4,5,6,10000]
array_dal_lista_numeri = np.array(lista)
array_dal_lista_numeri

array([    1,     2,     3,     4,     5,     6, 10000])

In [9]:
lista = [1,2,3,4,5,6,10000,"ciao"]
array_dal_lista_numeri = np.array(lista)
array_dal_lista_numeri

array(['1', '2', '3', '4', '5', '6', '10000', 'ciao'], dtype='<U11')

In [10]:
np.random.uniform(3,5)

4.314322648766413

In [11]:
float_casuali = np.random.uniform(3,5,10) # (numero di partenza, numero di arrivo, lunghezza array)
float_casuali

array([3.00694048, 3.57166925, 4.83657694, 3.28357604, 3.06189051,
       4.86713557, 4.82262023, 4.53815526, 4.57632687, 4.13592658])

In [12]:
int_casuali = np.random.randint(1,7,10)
int_casuali

array([5, 3, 5, 1, 1, 1, 4, 5, 3, 4])

In [13]:
alice = np.random.randint(1,7,10)
bob = np.random.randint(1,7,10)

In [14]:
print(f"Lanci del dado di Alice: {alice}")
print(f"Lanci del dado di Bob:   {bob}")

Lanci del dado di Alice: [4 6 4 2 3 2 6 3 2 2]
Lanci del dado di Bob:   [2 5 3 3 6 3 5 4 1 1]


In [15]:
alice > bob

array([ True,  True,  True, False, False, False,  True, False,  True,
        True])

In [16]:
print(f"Alice batte Bob {np.count_nonzero(alice > bob)} volte")

Alice batte Bob 6 volte


In [17]:
array_di_interi = np.arange(4,10)
array_di_interi

array([4, 5, 6, 7, 8, 9])

In [18]:
quadrati = np.arange(1,11)**2
quadrati

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [19]:
array1 = np.arange(1,5)
array1

array([1, 2, 3, 4])

In [20]:
array1.shape

(4,)

In [21]:
array2 = np.ones(4)
array2

array([1., 1., 1., 1.])

In [22]:
array1.dtype

dtype('int32')

In [23]:
array2.dtype

dtype('float64')

In [24]:
somma = array1+array2
somma

array([2., 3., 4., 5.])

In [25]:
somma.dtype

dtype('float64')

## Creazione di array 1D
array di zeri:
    
    np.zeros()

array di uni:
    
    np.ones()

array da liste:
    
    np.array()

array di interi crescenti:
    
    np.arange()

array pseudocasuali:
    
    np.random.randint()
    np.random.uniform()


### Array pseudo-casuali

In [26]:
np.random.randint(1,3,10)

array([1, 1, 2, 2, 2, 1, 1, 2, 2, 2])

In [27]:
np.random.uniform(0,1,10)

array([0.5149177 , 0.77590566, 0.09581108, 0.76511376, 0.27340015,
       0.33363565, 0.58389543, 0.39582339, 0.85782554, 0.75706381])

In [28]:
np.random.normal(175, 12, 10)

array([181.06058893, 167.7149006 , 183.57978384, 169.51468275,
       170.76213285, 179.71009524, 189.73035908, 151.80008867,
       184.61340171, 200.76692218])

In [29]:
altezze = np.random.normal(175, 2, 10)
altezze

array([174.43289973, 173.7261179 , 173.49049799, 174.67981151,
       176.47951891, 177.49181436, 175.29665363, 174.84917622,
       173.41781465, 174.69075971])

In [30]:
np.mean(altezze)

174.85550646213576

In [31]:
np.std(altezze)

1.2338767256232392

## Indicizzazione per booleani
Una delle funzioni più potenti di numpy

In [32]:
lanci_dadi = np.random.randint(1,7,10)
lanci_dadi

array([2, 1, 6, 1, 6, 5, 6, 1, 1, 2])

quali sono i lanci in cui il valore del dado era > 3

In [33]:
lanci_gt_3 = lanci_dadi > 3
lanci_gt_3

array([False, False,  True, False,  True,  True,  True, False, False,
       False])

In [34]:
lanci_dadi[lanci_gt_3] #indicizzo array con array di booleani

array([6, 6, 5, 6])

In [35]:
nomi = np.array(["Alice", "Bob", "Trudy", "Gigi"])
voti = np.array([6, 8, 2, 10])

Quali alunni sono sufficenti?

In [36]:
nomi[voti >= 6]

array(['Alice', 'Bob', 'Gigi'], dtype='<U5')

In [37]:
alice[alice > bob] #quando punteggi di alice quando vince

array([4, 6, 4, 6, 2, 2])

### Array bidimensionale
Es: 
- un'immagine in scale di grigi
- un'immagine RGB a colori è costituita da 3 array 2d
- un'immagine RGBA a colori è costituita da 4 array 2d (aggiunge la trasparenza)
- i dati in forma di tabella sono bidimensionali

In [38]:
matrice_di_zeri = np.zeros((3,6))
matrice_di_zeri

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [39]:
matrice_di_zeri.shape

(3, 6)

In [40]:
array_di_zeri = np.zeros(7)
array_di_zeri

array([0., 0., 0., 0., 0., 0., 0.])

In [41]:
array_di_zeri.shape

(7,)

In [42]:
np.ones((10,8), dtype=np.int8)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

In [43]:
np.array([[1,2,3],
         [4,5,'ciao']])

array([['1', '2', '3'],
       ['4', '5', 'ciao']], dtype='<U11')

In [44]:
np.random.randint(1,7,(10,2))

array([[6, 4],
       [6, 3],
       [3, 4],
       [1, 2],
       [6, 2],
       [6, 3],
       [2, 4],
       [3, 3],
       [5, 6],
       [6, 5]])

In [45]:
np.random.uniform(0,1, (4,4))

array([[0.68963866, 0.31616938, 0.79385309, 0.31950162],
       [0.00421063, 0.12341035, 0.72311942, 0.57992935],
       [0.41755701, 0.78405596, 0.5350577 , 0.04161308],
       [0.58530993, 0.74919067, 0.06526347, 0.19213407]])

In [46]:
array_3D = np.random.uniform(0,1, (3,3,2))
array_3D

array([[[0.78079292, 0.64727979],
        [0.55538386, 0.82203988],
        [0.61937842, 0.00544101]],

       [[0.88060482, 0.76339135],
        [0.6230263 , 0.00584646],
        [0.36611086, 0.50501641]],

       [[0.0168792 , 0.46739865],
        [0.20308389, 0.13686786],
        [0.16162311, 0.64286397]]])

In [47]:
array_3D.shape

(3, 3, 2)

### Operazioni matematiche di aggregazione
Per esempio:
- somma
- massimo/minimo
- media
- devazione standard
- somma cumulata

In [48]:
# somma
array = np.arange(1,101)
np.sum(array)

5050

In [49]:
#massimo/minimo
array = np.random.uniform(0,1,10)
array

array([0.80744053, 0.60934488, 0.67208417, 0.32779398, 0.62869588,
       0.17506744, 0.06095059, 0.92269356, 0.51206364, 0.63494075])

In [50]:
np.max(array) # trova il massimo

0.9226935569493907

In [51]:
np.std(array) # deviazione standard

0.25794399062297335

In [52]:
array_di_uni = np.ones(10)
array_di_uni

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [53]:
np.cumsum(array_di_uni)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [54]:
prezzo_apple = 178
variazioni = np.array([8, 3, -20, 6])

In [55]:
np.cumsum(variazioni) + prezzo_apple

array([186, 189, 169, 175])

### Cambiare forma di array

In [56]:
array_1d = np.arange(1,13)

In [57]:
array_1d.reshape((4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [58]:
array_1d.reshape((3,-1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### Esercizio
Dato n intero, generare l'array 2D fatto in questo modo:

        [[1,2,3,...,n],
         [1,2,3,...,n],
         ...
         ...
         [1,2,3,...,n]]
        
con n righe

In [59]:
n = 4
array1d = np.arange(1, n*n+1)
array2d = (array1d%n).reshape((n,-1))
array2d

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 2, 3, 0]], dtype=int32)

In [60]:
array2d = 1 + np.roll(array2d, 1)
array2d

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [61]:
array2d.reshape(-1)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [62]:
array2d.flatten()

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

### SLICING

In [63]:
array1d = np.arange(1,11)
array1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
array1d[3]

4

In [65]:
array1d[3:8]

array([4, 5, 6, 7, 8])

In [66]:
array1d[-1]

10

In [67]:
array1d[-2]

9

In [68]:
array1d[1:-1]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
array1d[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
array1d[3:8:2]

array([4, 6, 8])

In [71]:
np.random.seed(10)
array2d = np.random.uniform(0,1,(3,3))
array2d

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084]])

In [72]:
array2d[0,0]

0.771320643266746

In [73]:
array2d[1,2]

0.22479664553084766

In [74]:
array2d[1:]

array([[0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084]])

In [75]:
array2d[:,1:]

array([[0.02075195, 0.63364823],
       [0.49850701, 0.22479665],
       [0.76053071, 0.16911084]])

In [76]:
array2d[1:, 1:]

array([[0.49850701, 0.22479665],
       [0.76053071, 0.16911084]])

In [77]:
array2d[1:, 1:] = 0
array2d

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.        , 0.        ],
       [0.19806286, 0.        , 0.        ]])

### SUM E MAX

In [78]:
import numpy
vett = np.zeros((4,5))

In [79]:
np.sum(vett)

0.0

In [80]:
np.sum(vett, axis=1)

array([0., 0., 0., 0.])

In [81]:
np.max(vett)

0.0

In [82]:
np.max(vett, axis=1)

array([0., 0., 0., 0.])